// Renders the Lasso Cloud chain, price and error tables.
// Chains come from the live service manifest, errors from the error catalog
// the live OpenAPI document publishes, and prices from the account tariff
// file in lasso-cloud (config/account_model_cutover_tariff.exs), which is
// what Lasso charges.
// Usage: node scripts/cloud-catalog.mjs --tariff <path> [--check]
//          [--manifest <url-or-path>] [--openapi <url-or-path>]
// --check exits 1 when the committed snippets differ from the sources.
import {readFileSync, writeFileSync} from 'node:fs';

const args = process.argv.slice(2);
const option = name => {
  const index = args.indexOf(name);
  return index >= 0 ? args[index + 1] : undefined;
};
const check = args.includes('--check');
const source = option('--manifest') ?? 'https://lasso.sh/agent.json';
const tariffPath = option('--tariff');
if (!tariffPath) throw new Error('--tariff <path to account_model_cutover_tariff.exs> is required');

const load = async from =>
  from.startsWith('http')
    ? await (await fetch(from, {headers: {accept: 'application/json'}})).json()
    : JSON.parse(readFileSync(from, 'utf8'));
const manifest = await load(source);
const openapiSource = option('--openapi') ?? 'https://lasso.sh/openapi.json';
const catalog = (await load(openapiSource))['x-error-catalog'];
if (!catalog) throw new Error(`${openapiSource} publishes no x-error-catalog`);

const row = cells => `| ${cells.join(' | ')} |`;
const table = (head, rows) => [row(head), row(head.map(() => '---')), ...rows.map(row)].join('\n');

function parseTariff(text) {
  const version = text.match(/version:\s*"([^"]+)"/)?.[1];
  const unitNanos = Number(text.match(/unit_nanos:\s*([\d_]+)/)?.[1].replaceAll('_', ''));
  const block = name => text.match(new RegExp(`${name}:\\s*%\\{([\\s\\S]*?)\\n\\s*\\}`))?.[1] ?? '';
  const ratio = (body, key) => [...body.matchAll(key)].map(m => [m[1], Number(m[2]) / Number(m[3])]);
  const factors = Object.fromEntries(
    ratio(block('strategy_factors'), /(\w+):\s*\{(\d+),\s*(\d+)\}/g).map(([k, v]) => [k.replaceAll('_', '-'), v]),
  );
  const weights = Object.fromEntries(ratio(block('method_weights'), /"([^"]+)"\s*=>\s*\{(\d+),\s*(\d+)\}/g));
  if (!version || !unitNanos || Object.keys(factors).length === 0 || Object.keys(weights).length === 0) {
    throw new Error(`could not read the tariff at ${tariffPath}`);
  }
  return {version, unitNanos, factors, weights};
}

const usd = nanos => `$${(nanos / 1e9).toFixed(9).replace(/0+$/, '').replace(/\.$/, '')}`;

function chains({chains}) {
  if (!Array.isArray(chains) || chains.length === 0) throw new Error('manifest has no chains');
  const rows = [...chains]
    .sort((a, b) => a.chain_id - b.chain_id)
    .map(({name, chain_id}) => [`\`${name}\``, String(chain_id)]);
  return table(['Chain name', 'Chain ID'], rows);
}

// Lasso answers HTTP filter methods with -32601 (cloud/rpc-behavior), so the
// tariff's weights for them never apply.
const rejected = new Set([
  'eth_newFilter',
  'eth_newBlockFilter',
  'eth_newPendingTransactionFilter',
  'eth_getFilterChanges',
  'eth_getFilterLogs',
  'eth_uninstallFilter',
]);

function prices({unitNanos, factors, weights}) {
  const order = ['load-balanced', 'latency-weighted', 'fastest', 'priority'].filter(id => id in factors);
  const {_default: fallback, ...served} = weights;
  const named = Object.fromEntries(Object.entries(served).filter(([method]) => !rejected.has(method)));
  const cells = weight => [String(weight), ...order.map(id => usd(weight * factors[id] * unitNanos))];
  const rows = Object.keys(named).sort().map(method => [`\`${method}\``, ...cells(named[method])]);
  if (fallback) rows.push(['Any other method', ...cells(fallback)]);
  return table(['Method', 'Weight (CU)', ...order.map(id => `\`${id}\``)], rows);
}

// Pipes and line breaks would break a Markdown table cell; MDX reads < as a
// tag and { as an expression.
const cell = text =>
  String(text)
    .replaceAll('|', '\\|')
    .replaceAll('\n', ' ')
    .replaceAll('<', '&lt;')
    .replaceAll('{', '&#123;')
    .replaceAll('}', '&#125;');

function errors(entries, withRetry) {
  const rows = [...entries]
    .sort((a, b) => a.status - b.status || a.code.localeCompare(b.code))
    .map(e => [
      `\`${e.code}\``,
      String(e.status),
      ...(withRetry ? [e.retryable == null ? 'Varies' : e.retryable ? 'Yes' : 'No'] : []),
      cell(e.next_action),
    ]);
  return table(['Code', 'HTTP', ...(withRetry ? ['Retryable'] : []), 'Fix'], rows);
}

const tariff = parseTariff(readFileSync(tariffPath, 'utf8'));
const outputs = {
  'snippets/cloud-chains.mdx': [`{/* Generated by scripts/cloud-catalog.mjs from ${source}. Do not edit. */}`, chains(manifest)],
  'snippets/cloud-prices.mdx': [`{/* Generated by scripts/cloud-catalog.mjs from tariff ${tariff.version}. Do not edit. */}`, prices(tariff)],
  'snippets/cloud-errors-management.mdx': [`{/* Generated by scripts/cloud-catalog.mjs from the x-error-catalog in openapi.json. Do not edit. */}`, errors(catalog.management, false)],
  'snippets/cloud-errors-rpc.mdx': [`{/* Generated by scripts/cloud-catalog.mjs from the x-error-catalog in openapi.json. Do not edit. */}`, errors(catalog.rpc, true)],
};

let drift = false;
for (const [path, [banner, body]] of Object.entries(outputs)) {
  const text = `${banner}\n\n${body}\n`;
  if (!check) {
    writeFileSync(path, text);
    continue;
  }
  let current = '';
  try {
    current = readFileSync(path, 'utf8');
  } catch {}
  if (current !== text) {
    drift = true;
    console.error(`${path} differs from its source; run node scripts/cloud-catalog.mjs --tariff <path>`);
  }
}

if (drift) process.exit(1);
console.log(`Cloud catalog ${check ? 'matches' : 'written from'} ${source}, ${openapiSource} and tariff ${tariff.version}`);
