// Renders the Lasso Cloud chain and price tables from the live service manifest.
// Usage: node scripts/cloud-catalog.mjs [--check] [--manifest <url-or-path>]
// --check exits 1 when the committed snippets differ from the manifest.
import {readFileSync, writeFileSync} from 'node:fs';

const args = process.argv.slice(2);
const check = args.includes('--check');
const flag = args.indexOf('--manifest');
const source = flag >= 0 ? args[flag + 1] : 'https://lasso.sh/agent.json';

const manifest = source.startsWith('http')
  ? await (await fetch(source, {headers: {accept: 'application/json'}})).json()
  : JSON.parse(readFileSync(source, 'utf8'));

const banner = `{/* Generated by scripts/cloud-catalog.mjs from ${source}. Do not edit. */}`;
const row = cells => `| ${cells.join(' | ')} |`;
const table = (head, rows) => [row(head), row(head.map(() => '---')), ...rows.map(row)].join('\n');

function chains({chains}) {
  if (!Array.isArray(chains) || chains.length === 0) throw new Error('manifest has no chains');
  const rows = [...chains]
    .sort((a, b) => a.chain_id - b.chain_id)
    .map(({name, chain_id}) => [`\`${name}\``, String(chain_id)]);
  return table(['Chain name', 'Chain ID'], rows);
}

function prices({pricing, strategies}) {
  const methods = pricing?.methods;
  if (!methods || typeof methods !== 'object') throw new Error('manifest has no pricing.methods');
  const order = strategies.map(({id}) => id);
  const {_default: fallback, ...named} = methods;
  const rows = Object.keys(named)
    .sort()
    .map(method => [`\`${method}\``, ...order.map(id => `$${named[method][id]}`)]);
  if (fallback) rows.push(['Any other method', ...order.map(id => `$${fallback[id]}`)]);
  return table(['Method', ...order.map(id => `\`${id}\``)], rows);
}

const outputs = {
  'snippets/cloud-chains.mdx': chains(manifest),
  'snippets/cloud-prices.mdx': prices(manifest),
};

let drift = false;
for (const [path, body] of Object.entries(outputs)) {
  const text = `${banner}\n\n${body}\n`;
  if (!check) {
    writeFileSync(path, text);
    continue;
  }
  let current = '';
  try {
    current = readFileSync(path, 'utf8');
  } catch {}
  if (current !== text) {
    drift = true;
    console.error(`${path} differs from ${source}; run node scripts/cloud-catalog.mjs`);
  }
}

if (drift) process.exit(1);
console.log(check ? `Cloud catalog matches ${source}` : `Cloud catalog written from ${source}`);
